name: Renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry-run mode"
        type: boolean
        required: false
        default: false

jobs:
  renovate:
    runs-on: windows-latest

    steps:
      - name: Checkout Renovate
        uses: actions/checkout@v6
        with:
          repository: reduckted/renovate
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"

      - name: Enable corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - name: Run Renovate
        run: |
          pnpm run start
        env:
          LOG_LEVEL: ${{ inputs.dry-run && 'debug' || 'info' }}
          RENOVATE_ALLOWED_COMMANDS: "^pwsh"
          RENOVATE_DRY_RUN: ${{ inputs.dry-run && 'full' || '' }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: reduckted/test-renovate
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
