name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: reduckted/test-renovate-actions/alpha@1.0.0+alpha
      - uses: reduckted/test-renovate-actions/alpha@1.0.0+beta
      - uses: reduckted/test-renovate-actions/alpha@1.0.0+gamma
